### ISSUE TITLE
Bootloader not ready in time.

### ISSUE THREAD

**Issue by darkxst** [NabuCasa/universal-silabs-flasher#38]
I'm occasionally hitting this error on the ZBDongle-E, switching between RCP multipan firmware builds. It probably takes 3-4 attempts to reproduce this error. Probing the  bootloader baudrate fails with invalid app type, but if I connect to the serial port straight after the error it is in bootloader.

Not been able to catch it in debugger, but my guess is bootloader is not ready at this time. Maybe need to add a small delay after sending the CPC reset?

```
(py310) tim@xt:/usr/local/src/raspi/zbdongle-E/universal-silabs-flasher$ python -m universal_silabs_flasher --device=/dev/ttyACM0 flash --firmware ~/Downloads/rcp-uart-802154-zbdonglee-230400.gbl 
2023-04-25 18:58:19 xt universal_silabs_flasher.flash[1527175] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.2.2', ezsp_version=None, ot_rcp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=230400)
2023-04-25 18:58:19 xt universal_silabs_flasher.flasher[1527175] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-04-25 18:58:21 xt universal_silabs_flasher.flasher[1527175] INFO Probing ApplicationType.CPC at 460800 baud
2023-04-25 18:58:21 xt universal_silabs_flasher.flasher[1527175] INFO Detected ApplicationType.CPC, version '4.2.2' at 460800 baudrate (bootloader baudrate None)
2023-04-25 18:58:21 xt universal_silabs_flasher.flash[1527175] INFO Firmware baudrate 460800 differs from expected baudrate 230400
2023-04-25 18:58:21 xt universal_silabs_flasher.flasher[1527175] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
Traceback (most recent call last):
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/src/raspi/zbdongle-E/universal-silabs-flasher/universal_silabs_flasher/__main__.py", line 4, in <module>
    main()
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/src/raspi/zbdongle-E/universal-silabs-flasher/universal_silabs_flasher/flash.py", line 35, in inner
    return asyncio.run(f(*args, **kwargs))
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/tim/anaconda3/envs/py310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/src/raspi/zbdongle-E/universal-silabs-flasher/universal_silabs_flasher/flash.py", line 369, in flash
    await flasher.enter_bootloader()
  File "/usr/local/src/raspi/zbdongle-E/universal-silabs-flasher/universal_silabs_flasher/flasher.py", line 305, in enter_bootloader
    await self.probe_app_type(types=[ApplicationType.GECKO_BOOTLOADER])
  File "/usr/local/src/raspi/zbdongle-E/universal-silabs-flasher/universal_silabs_flasher/flasher.py", line 261, in probe_app_type
    raise RuntimeError("Failed to probe running application type")
RuntimeError: Failed to probe running application type
```

**Comment by darkxst** [comment]
Also it seems to happen more frequently when CPC baudrate is 460800..
