### ISSUE TITLE
Flasher problem with HomeAssistant Yellow / Silicon Labs Multiprotocol

### ISSUE THREAD

**Issue by ddrager** [NabuCasa/universal-silabs-flasher#5]
When trying to enable Silicon Labs Multiprotocol, with the "Update firmare" option enabled, service fails because of failure to update firmware. Here is the log:

``` System: Home Assistant OS 9.3  (aarch64 / yellow)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[12:22:06] INFO: Detected Home Assistant Yellow
[12:22:06] INFO: Starting universal-silabs-flasher with /dev/ttyAMA1 (baudrate 115200)
2022-11-16 12:22:07 core-silabs-multiprotocol universal_silabs_flasher.flash[206] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.1.3'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2022-11-16 12:22:07 core-silabs-multiprotocol universal_silabs_flasher.flash[206] INFO Connecting with Gecko bootloader
2022-11-16 12:22:09 core-silabs-multiprotocol universal_silabs_flasher.flash[206] INFO Connecting with EZSP
2022-11-16 12:22:14 core-silabs-multiprotocol universal_silabs_flasher.flash[206] INFO Connecting with CPC
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 211, in _get_application_version
    await cpc.probe()
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/cpc.py", line 219, in probe
    return await self.get_cpc_version()
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/cpc.py", line 238, in get_cpc_version
    rsp = await self.send_unnumbered_frame(
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/cpc.py", line 334, in send_unnumbered_frame
    return await asyncio.shield(future)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 211, in _get_application_version
    await cpc.probe()
  File "/usr/lib/python3/dist-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/lib/python3/dist-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/universal-silabs-flasher", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 39, in inner
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 293, in flash
    app_version, application_type = await _get_application_version(ctx)
  File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 213, in _get_application_version
    raise RuntimeError("Failed to probe CPC")
RuntimeError: Failed to probe CPC
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1```

**Comment by puddly** [comment]
Was this with a Yellow previously used with ZHA? Is it possible that another addon or integration is accessing the radio?

**Comment by ddrager** [comment]
Nope this is a brand new install, I did install Matter and SSH add-on, but disabled Matter just in case, same issue. I'm in the #yellow channel in Discord if it helps.
