### ISSUE TITLE
Flashing successful but can not write IEEE

### ISSUE THREAD

**Issue by jmaire87** [NabuCasa/universal-silabs-flasher#89]
Hey

When trying to write IEEE address to the sonoff EFR32MG21 Zigbee stick, I get the error below
I've been flashing the software successfully 5 min before. Flasher version is 0.24

Thanks the help

```
(pyEnv) admin@MacBook-Pro-de-A ~ % universal-silabs-flasher --device /dev/cu.SLAB_USBtoUART --ezsp-baudrate 115200  write-ieee --ieee 34:f5:27:ff:fe:78:2b:75

2024-11-05 23:50:50.567 MacBook-Pro-de-A.local universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2024-11-05 23:50:54.608 MacBook-Pro-de-A.local universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 460800 baud
2024-11-05 23:51:00.966 MacBook-Pro-de-A.local universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 115200 baud
2024-11-05 23:51:07.315 MacBook-Pro-de-A.local universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 230400 baud
2024-11-05 23:51:13.666 MacBook-Pro-de-A.local universal_silabs_flasher.flasher INFO Probing ApplicationType.EZSP at 115200 baud
2024-11-05 23:51:16.864 MacBook-Pro-de-A.local universal_silabs_flasher.flasher INFO Detected ApplicationType.EZSP, version '7.4.4.0 build 0' (7.4.4.0.0) at 115200 baudrate (bootloader baudrate None)
2024-11-05 23:51:18.506 MacBook-Pro-de-A.local universal_silabs_flasher.flasher INFO Current device IEEE: 8c:65:a3:ff:fe:52:74:f0
Traceback (most recent call last):
  File "/Users/admin/pyEnv/bin/universal-silabs-flasher", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/universal_silabs_flasher/flash.py", line 38, in inner
    return asyncio.run(f(*args, **kwargs))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/universal_silabs_flasher/flash.py", line 256, in write_ieee
    await ctx.obj["flasher"].write_emberznet_eui64(new_eui64)
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/universal_silabs_flasher/flasher.py", line 319, in write_emberznet_eui64
    if not await ezsp.can_write_custom_eui64():
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/bellows/ezsp/__init__.py", line 271, in __getattr__
    return getattr(self._protocol, name)
  File "/Users/admin/pyEnv/lib/python3.13/site-packages/bellows/ezsp/protocol.py", line 205, in __getattr__
    raise AttributeError(f"{name} not found in COMMANDS")
AttributeError: can_write_custom_eui64 not found in COMMANDS
```

**Comment by jmaire87** [comment]
Version 0.25 solved this issue
Thank you guys for your work
